// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: forest.proto

package forest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Children      []*Tree                `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tree) Reset() {
	*x = Tree{}
	mi := &file_forest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tree) ProtoMessage() {}

func (x *Tree) ProtoReflect() protoreflect.Message {
	mi := &file_forest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tree.ProtoReflect.Descriptor instead.
func (*Tree) Descriptor() ([]byte, []int) {
	return file_forest_proto_rawDescGZIP(), []int{0}
}

func (x *Tree) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tree) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tree) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Tree) GetChildren() []*Tree {
	if x != nil {
		return x.Children
	}
	return nil
}

type CreateTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	ParentId      string                 `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTreeRequest) Reset() {
	*x = CreateTreeRequest{}
	mi := &file_forest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTreeRequest) ProtoMessage() {}

func (x *CreateTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTreeRequest.ProtoReflect.Descriptor instead.
func (*CreateTreeRequest) Descriptor() ([]byte, []int) {
	return file_forest_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTreeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateTreeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTreeRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateTreeRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type Forest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Root          *Tree                  `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Depth         int32                  `protobuf:"varint,5,opt,name=depth,proto3" json:"depth,omitempty"`
	TotalTrees    int32                  `protobuf:"varint,6,opt,name=total_trees,json=totalTrees,proto3" json:"total_trees,omitempty"`
	UserId        string                 `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Forest) Reset() {
	*x = Forest{}
	mi := &file_forest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Forest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forest) ProtoMessage() {}

func (x *Forest) ProtoReflect() protoreflect.Message {
	mi := &file_forest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forest.ProtoReflect.Descriptor instead.
func (*Forest) Descriptor() ([]byte, []int) {
	return file_forest_proto_rawDescGZIP(), []int{2}
}

func (x *Forest) GetRoot() *Tree {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *Forest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Forest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Forest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Forest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *Forest) GetTotalTrees() int32 {
	if x != nil {
		return x.TotalTrees
	}
	return 0
}

func (x *Forest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateForestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Root          *Tree                  `protobuf:"bytes,4,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateForestRequest) Reset() {
	*x = CreateForestRequest{}
	mi := &file_forest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateForestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateForestRequest) ProtoMessage() {}

func (x *CreateForestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateForestRequest.ProtoReflect.Descriptor instead.
func (*CreateForestRequest) Descriptor() ([]byte, []int) {
	return file_forest_proto_rawDescGZIP(), []int{3}
}

func (x *CreateForestRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateForestRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateForestRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateForestRequest) GetRoot() *Tree {
	if x != nil {
		return x.Root
	}
	return nil
}

type GetForestsByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForestsByUserRequest) Reset() {
	*x = GetForestsByUserRequest{}
	mi := &file_forest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForestsByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForestsByUserRequest) ProtoMessage() {}

func (x *GetForestsByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForestsByUserRequest.ProtoReflect.Descriptor instead.
func (*GetForestsByUserRequest) Descriptor() ([]byte, []int) {
	return file_forest_proto_rawDescGZIP(), []int{4}
}

func (x *GetForestsByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetForestsByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Forests       []*Forest              `protobuf:"bytes,1,rep,name=forests,proto3" json:"forests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForestsByUserResponse) Reset() {
	*x = GetForestsByUserResponse{}
	mi := &file_forest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForestsByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForestsByUserResponse) ProtoMessage() {}

func (x *GetForestsByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForestsByUserResponse.ProtoReflect.Descriptor instead.
func (*GetForestsByUserResponse) Descriptor() ([]byte, []int) {
	return file_forest_proto_rawDescGZIP(), []int{5}
}

func (x *GetForestsByUserResponse) GetForests() []*Forest {
	if x != nil {
		return x.Forests
	}
	return nil
}

type GetForestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ForestId      string                 `protobuf:"bytes,1,opt,name=forest_id,json=forestId,proto3" json:"forest_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForestRequest) Reset() {
	*x = GetForestRequest{}
	mi := &file_forest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForestRequest) ProtoMessage() {}

func (x *GetForestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForestRequest.ProtoReflect.Descriptor instead.
func (*GetForestRequest) Descriptor() ([]byte, []int) {
	return file_forest_proto_rawDescGZIP(), []int{6}
}

func (x *GetForestRequest) GetForestId() string {
	if x != nil {
		return x.ForestId
	}
	return ""
}

type GetForestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Forest        *Forest                `protobuf:"bytes,1,opt,name=forest,proto3" json:"forest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForestResponse) Reset() {
	*x = GetForestResponse{}
	mi := &file_forest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForestResponse) ProtoMessage() {}

func (x *GetForestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForestResponse.ProtoReflect.Descriptor instead.
func (*GetForestResponse) Descriptor() ([]byte, []int) {
	return file_forest_proto_rawDescGZIP(), []int{7}
}

func (x *GetForestResponse) GetForest() *Forest {
	if x != nil {
		return x.Forest
	}
	return nil
}

var File_forest_proto protoreflect.FileDescriptor

const file_forest_proto_rawDesc = "" +
	"\n" +
	"\fforest.proto\"_\n" +
	"\x04Tree\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12!\n" +
	"\bchildren\x18\x04 \x03(\v2\x05.TreeR\bchildren\"f\n" +
	"\x11CreateTreeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\tR\bparentId\"\xb9\x01\n" +
	"\x06Forest\x12\x19\n" +
	"\x04root\x18\x01 \x01(\v2\x05.TreeR\x04root\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05depth\x18\x05 \x01(\x05R\x05depth\x12\x1f\n" +
	"\vtotal_trees\x18\x06 \x01(\x05R\n" +
	"totalTrees\x12\x17\n" +
	"\auser_id\x18\a \x01(\tR\x06userId\"\x7f\n" +
	"\x13CreateForestRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x19\n" +
	"\x04root\x18\x04 \x01(\v2\x05.TreeR\x04root\"2\n" +
	"\x17GetForestsByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"=\n" +
	"\x18GetForestsByUserResponse\x12!\n" +
	"\aforests\x18\x01 \x03(\v2\a.ForestR\aforests\"/\n" +
	"\x10GetForestRequest\x12\x1b\n" +
	"\tforest_id\x18\x01 \x01(\tR\bforestId\"4\n" +
	"\x11GetForestResponse\x12\x1f\n" +
	"\x06forest\x18\x01 \x01(\v2\a.ForestR\x06forest2\xea\x01\n" +
	"\rForestService\x12I\n" +
	"\x10GetForestsByUser\x12\x18.GetForestsByUserRequest\x1a\x19.GetForestsByUserResponse\"\x00\x12/\n" +
	"\fCreateForest\x12\x14.CreateForestRequest\x1a\a.Forest\"\x00\x12)\n" +
	"\n" +
	"CreateTree\x12\x12.CreateTreeRequest\x1a\x05.Tree\"\x00\x122\n" +
	"\tGetForest\x12\x11.GetForestRequest\x1a\x12.GetForestResponseB2Z0github.com/jdk829355/INForest_back/protos/forestb\x06proto3"

var (
	file_forest_proto_rawDescOnce sync.Once
	file_forest_proto_rawDescData []byte
)

func file_forest_proto_rawDescGZIP() []byte {
	file_forest_proto_rawDescOnce.Do(func() {
		file_forest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_forest_proto_rawDesc), len(file_forest_proto_rawDesc)))
	})
	return file_forest_proto_rawDescData
}

var file_forest_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_forest_proto_goTypes = []any{
	(*Tree)(nil),                     // 0: Tree
	(*CreateTreeRequest)(nil),        // 1: CreateTreeRequest
	(*Forest)(nil),                   // 2: Forest
	(*CreateForestRequest)(nil),      // 3: CreateForestRequest
	(*GetForestsByUserRequest)(nil),  // 4: GetForestsByUserRequest
	(*GetForestsByUserResponse)(nil), // 5: GetForestsByUserResponse
	(*GetForestRequest)(nil),         // 6: GetForestRequest
	(*GetForestResponse)(nil),        // 7: GetForestResponse
}
var file_forest_proto_depIdxs = []int32{
	0, // 0: Tree.children:type_name -> Tree
	0, // 1: Forest.root:type_name -> Tree
	0, // 2: CreateForestRequest.root:type_name -> Tree
	2, // 3: GetForestsByUserResponse.forests:type_name -> Forest
	2, // 4: GetForestResponse.forest:type_name -> Forest
	4, // 5: ForestService.GetForestsByUser:input_type -> GetForestsByUserRequest
	3, // 6: ForestService.CreateForest:input_type -> CreateForestRequest
	1, // 7: ForestService.CreateTree:input_type -> CreateTreeRequest
	6, // 8: ForestService.GetForest:input_type -> GetForestRequest
	5, // 9: ForestService.GetForestsByUser:output_type -> GetForestsByUserResponse
	2, // 10: ForestService.CreateForest:output_type -> Forest
	0, // 11: ForestService.CreateTree:output_type -> Tree
	7, // 12: ForestService.GetForest:output_type -> GetForestResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_forest_proto_init() }
func file_forest_proto_init() {
	if File_forest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_forest_proto_rawDesc), len(file_forest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_forest_proto_goTypes,
		DependencyIndexes: file_forest_proto_depIdxs,
		MessageInfos:      file_forest_proto_msgTypes,
	}.Build()
	File_forest_proto = out.File
	file_forest_proto_goTypes = nil
	file_forest_proto_depIdxs = nil
}
