// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: protos/forest/forest.proto

package forest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ForestService_GetForestsByUser_FullMethodName = "/ForestService/GetForestsByUser"
	ForestService_GetForest_FullMethodName        = "/ForestService/GetForest"
	ForestService_GetTree_FullMethodName          = "/ForestService/GetTree"
	ForestService_CreateForest_FullMethodName     = "/ForestService/CreateForest"
	ForestService_CreateTree_FullMethodName       = "/ForestService/CreateTree"
	ForestService_UpdateForest_FullMethodName     = "/ForestService/UpdateForest"
	ForestService_UpdateTree_FullMethodName       = "/ForestService/UpdateTree"
	ForestService_DeleteForest_FullMethodName     = "/ForestService/DeleteForest"
	ForestService_DeleteTree_FullMethodName       = "/ForestService/DeleteTree"
	ForestService_UpdateMemo_FullMethodName       = "/ForestService/UpdateMemo"
	ForestService_GetMemo_FullMethodName          = "/ForestService/GetMemo"
)

// ForestServiceClient is the client API for ForestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ForestService는 숲과 나무에 대한 CRUD 작업을 처리합니다.
type ForestServiceClient interface {
	GetForestsByUser(ctx context.Context, in *GetForestsByUserRequest, opts ...grpc.CallOption) (*GetForestsByUserResponse, error)
	GetForest(ctx context.Context, in *GetForestRequest, opts ...grpc.CallOption) (*GetForestResponse, error)
	GetTree(ctx context.Context, in *GetTreeRequest, opts ...grpc.CallOption) (*Tree, error)
	CreateForest(ctx context.Context, in *CreateForestRequest, opts ...grpc.CallOption) (*Forest, error)
	CreateTree(ctx context.Context, in *CreateTreeRequest, opts ...grpc.CallOption) (*CreateTreeResponse, error)
	UpdateForest(ctx context.Context, in *UpdateForestRequest, opts ...grpc.CallOption) (*Forest, error)
	UpdateTree(ctx context.Context, in *UpdateTreeRequest, opts ...grpc.CallOption) (*Tree, error)
	DeleteForest(ctx context.Context, in *DeleteForestRequest, opts ...grpc.CallOption) (*DeleteForestResponse, error)
	DeleteTree(ctx context.Context, in *DeleteTreeRequest, opts ...grpc.CallOption) (*DeleteTreeResponse, error)
	UpdateMemo(ctx context.Context, in *UpdateMemoRequest, opts ...grpc.CallOption) (*UpdateMemoResponse, error)
	GetMemo(ctx context.Context, in *GetMemoRequest, opts ...grpc.CallOption) (*Memo, error)
}

type forestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewForestServiceClient(cc grpc.ClientConnInterface) ForestServiceClient {
	return &forestServiceClient{cc}
}

func (c *forestServiceClient) GetForestsByUser(ctx context.Context, in *GetForestsByUserRequest, opts ...grpc.CallOption) (*GetForestsByUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetForestsByUserResponse)
	err := c.cc.Invoke(ctx, ForestService_GetForestsByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forestServiceClient) GetForest(ctx context.Context, in *GetForestRequest, opts ...grpc.CallOption) (*GetForestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetForestResponse)
	err := c.cc.Invoke(ctx, ForestService_GetForest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forestServiceClient) GetTree(ctx context.Context, in *GetTreeRequest, opts ...grpc.CallOption) (*Tree, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tree)
	err := c.cc.Invoke(ctx, ForestService_GetTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forestServiceClient) CreateForest(ctx context.Context, in *CreateForestRequest, opts ...grpc.CallOption) (*Forest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Forest)
	err := c.cc.Invoke(ctx, ForestService_CreateForest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forestServiceClient) CreateTree(ctx context.Context, in *CreateTreeRequest, opts ...grpc.CallOption) (*CreateTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTreeResponse)
	err := c.cc.Invoke(ctx, ForestService_CreateTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forestServiceClient) UpdateForest(ctx context.Context, in *UpdateForestRequest, opts ...grpc.CallOption) (*Forest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Forest)
	err := c.cc.Invoke(ctx, ForestService_UpdateForest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forestServiceClient) UpdateTree(ctx context.Context, in *UpdateTreeRequest, opts ...grpc.CallOption) (*Tree, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tree)
	err := c.cc.Invoke(ctx, ForestService_UpdateTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forestServiceClient) DeleteForest(ctx context.Context, in *DeleteForestRequest, opts ...grpc.CallOption) (*DeleteForestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteForestResponse)
	err := c.cc.Invoke(ctx, ForestService_DeleteForest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forestServiceClient) DeleteTree(ctx context.Context, in *DeleteTreeRequest, opts ...grpc.CallOption) (*DeleteTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTreeResponse)
	err := c.cc.Invoke(ctx, ForestService_DeleteTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forestServiceClient) UpdateMemo(ctx context.Context, in *UpdateMemoRequest, opts ...grpc.CallOption) (*UpdateMemoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMemoResponse)
	err := c.cc.Invoke(ctx, ForestService_UpdateMemo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forestServiceClient) GetMemo(ctx context.Context, in *GetMemoRequest, opts ...grpc.CallOption) (*Memo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Memo)
	err := c.cc.Invoke(ctx, ForestService_GetMemo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ForestServiceServer is the server API for ForestService service.
// All implementations must embed UnimplementedForestServiceServer
// for forward compatibility.
//
// ForestService는 숲과 나무에 대한 CRUD 작업을 처리합니다.
type ForestServiceServer interface {
	GetForestsByUser(context.Context, *GetForestsByUserRequest) (*GetForestsByUserResponse, error)
	GetForest(context.Context, *GetForestRequest) (*GetForestResponse, error)
	GetTree(context.Context, *GetTreeRequest) (*Tree, error)
	CreateForest(context.Context, *CreateForestRequest) (*Forest, error)
	CreateTree(context.Context, *CreateTreeRequest) (*CreateTreeResponse, error)
	UpdateForest(context.Context, *UpdateForestRequest) (*Forest, error)
	UpdateTree(context.Context, *UpdateTreeRequest) (*Tree, error)
	DeleteForest(context.Context, *DeleteForestRequest) (*DeleteForestResponse, error)
	DeleteTree(context.Context, *DeleteTreeRequest) (*DeleteTreeResponse, error)
	UpdateMemo(context.Context, *UpdateMemoRequest) (*UpdateMemoResponse, error)
	GetMemo(context.Context, *GetMemoRequest) (*Memo, error)
	mustEmbedUnimplementedForestServiceServer()
}

// UnimplementedForestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedForestServiceServer struct{}

func (UnimplementedForestServiceServer) GetForestsByUser(context.Context, *GetForestsByUserRequest) (*GetForestsByUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetForestsByUser not implemented")
}
func (UnimplementedForestServiceServer) GetForest(context.Context, *GetForestRequest) (*GetForestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetForest not implemented")
}
func (UnimplementedForestServiceServer) GetTree(context.Context, *GetTreeRequest) (*Tree, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTree not implemented")
}
func (UnimplementedForestServiceServer) CreateForest(context.Context, *CreateForestRequest) (*Forest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateForest not implemented")
}
func (UnimplementedForestServiceServer) CreateTree(context.Context, *CreateTreeRequest) (*CreateTreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTree not implemented")
}
func (UnimplementedForestServiceServer) UpdateForest(context.Context, *UpdateForestRequest) (*Forest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateForest not implemented")
}
func (UnimplementedForestServiceServer) UpdateTree(context.Context, *UpdateTreeRequest) (*Tree, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTree not implemented")
}
func (UnimplementedForestServiceServer) DeleteForest(context.Context, *DeleteForestRequest) (*DeleteForestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteForest not implemented")
}
func (UnimplementedForestServiceServer) DeleteTree(context.Context, *DeleteTreeRequest) (*DeleteTreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTree not implemented")
}
func (UnimplementedForestServiceServer) UpdateMemo(context.Context, *UpdateMemoRequest) (*UpdateMemoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMemo not implemented")
}
func (UnimplementedForestServiceServer) GetMemo(context.Context, *GetMemoRequest) (*Memo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMemo not implemented")
}
func (UnimplementedForestServiceServer) mustEmbedUnimplementedForestServiceServer() {}
func (UnimplementedForestServiceServer) testEmbeddedByValue()                       {}

// UnsafeForestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForestServiceServer will
// result in compilation errors.
type UnsafeForestServiceServer interface {
	mustEmbedUnimplementedForestServiceServer()
}

func RegisterForestServiceServer(s grpc.ServiceRegistrar, srv ForestServiceServer) {
	// If the following call pancis, it indicates UnimplementedForestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ForestService_ServiceDesc, srv)
}

func _ForestService_GetForestsByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetForestsByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForestServiceServer).GetForestsByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForestService_GetForestsByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForestServiceServer).GetForestsByUser(ctx, req.(*GetForestsByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForestService_GetForest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetForestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForestServiceServer).GetForest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForestService_GetForest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForestServiceServer).GetForest(ctx, req.(*GetForestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForestService_GetTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForestServiceServer).GetTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForestService_GetTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForestServiceServer).GetTree(ctx, req.(*GetTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForestService_CreateForest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateForestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForestServiceServer).CreateForest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForestService_CreateForest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForestServiceServer).CreateForest(ctx, req.(*CreateForestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForestService_CreateTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForestServiceServer).CreateTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForestService_CreateTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForestServiceServer).CreateTree(ctx, req.(*CreateTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForestService_UpdateForest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateForestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForestServiceServer).UpdateForest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForestService_UpdateForest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForestServiceServer).UpdateForest(ctx, req.(*UpdateForestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForestService_UpdateTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForestServiceServer).UpdateTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForestService_UpdateTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForestServiceServer).UpdateTree(ctx, req.(*UpdateTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForestService_DeleteForest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteForestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForestServiceServer).DeleteForest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForestService_DeleteForest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForestServiceServer).DeleteForest(ctx, req.(*DeleteForestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForestService_DeleteTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForestServiceServer).DeleteTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForestService_DeleteTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForestServiceServer).DeleteTree(ctx, req.(*DeleteTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForestService_UpdateMemo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMemoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForestServiceServer).UpdateMemo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForestService_UpdateMemo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForestServiceServer).UpdateMemo(ctx, req.(*UpdateMemoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForestService_GetMemo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForestServiceServer).GetMemo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForestService_GetMemo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForestServiceServer).GetMemo(ctx, req.(*GetMemoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ForestService_ServiceDesc is the grpc.ServiceDesc for ForestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ForestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ForestService",
	HandlerType: (*ForestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetForestsByUser",
			Handler:    _ForestService_GetForestsByUser_Handler,
		},
		{
			MethodName: "GetForest",
			Handler:    _ForestService_GetForest_Handler,
		},
		{
			MethodName: "GetTree",
			Handler:    _ForestService_GetTree_Handler,
		},
		{
			MethodName: "CreateForest",
			Handler:    _ForestService_CreateForest_Handler,
		},
		{
			MethodName: "CreateTree",
			Handler:    _ForestService_CreateTree_Handler,
		},
		{
			MethodName: "UpdateForest",
			Handler:    _ForestService_UpdateForest_Handler,
		},
		{
			MethodName: "UpdateTree",
			Handler:    _ForestService_UpdateTree_Handler,
		},
		{
			MethodName: "DeleteForest",
			Handler:    _ForestService_DeleteForest_Handler,
		},
		{
			MethodName: "DeleteTree",
			Handler:    _ForestService_DeleteTree_Handler,
		},
		{
			MethodName: "UpdateMemo",
			Handler:    _ForestService_UpdateMemo_Handler,
		},
		{
			MethodName: "GetMemo",
			Handler:    _ForestService_GetMemo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/forest/forest.proto",
}
