// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: protos/forest/forest.proto

package forest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetForestsByUserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IncludeChildren bool                   `protobuf:"varint,1,opt,name=include_children,json=includeChildren,proto3" json:"include_children,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetForestsByUserRequest) Reset() {
	*x = GetForestsByUserRequest{}
	mi := &file_protos_forest_forest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForestsByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForestsByUserRequest) ProtoMessage() {}

func (x *GetForestsByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_forest_forest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForestsByUserRequest.ProtoReflect.Descriptor instead.
func (*GetForestsByUserRequest) Descriptor() ([]byte, []int) {
	return file_protos_forest_forest_proto_rawDescGZIP(), []int{0}
}

func (x *GetForestsByUserRequest) GetIncludeChildren() bool {
	if x != nil {
		return x.IncludeChildren
	}
	return false
}

type Tree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Children      []*Tree                `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tree) Reset() {
	*x = Tree{}
	mi := &file_protos_forest_forest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tree) ProtoMessage() {}

func (x *Tree) ProtoReflect() protoreflect.Message {
	mi := &file_protos_forest_forest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tree.ProtoReflect.Descriptor instead.
func (*Tree) Descriptor() ([]byte, []int) {
	return file_protos_forest_forest_proto_rawDescGZIP(), []int{1}
}

func (x *Tree) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tree) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tree) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Tree) GetChildren() []*Tree {
	if x != nil {
		return x.Children
	}
	return nil
}

type CreateTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	ParentId      string                 `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTreeRequest) Reset() {
	*x = CreateTreeRequest{}
	mi := &file_protos_forest_forest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTreeRequest) ProtoMessage() {}

func (x *CreateTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_forest_forest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTreeRequest.ProtoReflect.Descriptor instead.
func (*CreateTreeRequest) Descriptor() ([]byte, []int) {
	return file_protos_forest_forest_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTreeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateTreeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTreeRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateTreeRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type Forest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Root          *Tree                  `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Depth         int32                  `protobuf:"varint,5,opt,name=depth,proto3" json:"depth,omitempty"`
	TotalTrees    int32                  `protobuf:"varint,6,opt,name=total_trees,json=totalTrees,proto3" json:"total_trees,omitempty"`
	UserId        string                 `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Forest) Reset() {
	*x = Forest{}
	mi := &file_protos_forest_forest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Forest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forest) ProtoMessage() {}

func (x *Forest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_forest_forest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forest.ProtoReflect.Descriptor instead.
func (*Forest) Descriptor() ([]byte, []int) {
	return file_protos_forest_forest_proto_rawDescGZIP(), []int{3}
}

func (x *Forest) GetRoot() *Tree {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *Forest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Forest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Forest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Forest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *Forest) GetTotalTrees() int32 {
	if x != nil {
		return x.TotalTrees
	}
	return 0
}

func (x *Forest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateForestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Root          *Tree                  `protobuf:"bytes,4,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateForestRequest) Reset() {
	*x = CreateForestRequest{}
	mi := &file_protos_forest_forest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateForestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateForestRequest) ProtoMessage() {}

func (x *CreateForestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_forest_forest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateForestRequest.ProtoReflect.Descriptor instead.
func (*CreateForestRequest) Descriptor() ([]byte, []int) {
	return file_protos_forest_forest_proto_rawDescGZIP(), []int{4}
}

func (x *CreateForestRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateForestRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateForestRequest) GetRoot() *Tree {
	if x != nil {
		return x.Root
	}
	return nil
}

type GetForestsByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Forests       []*Forest              `protobuf:"bytes,1,rep,name=forests,proto3" json:"forests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForestsByUserResponse) Reset() {
	*x = GetForestsByUserResponse{}
	mi := &file_protos_forest_forest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForestsByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForestsByUserResponse) ProtoMessage() {}

func (x *GetForestsByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_forest_forest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForestsByUserResponse.ProtoReflect.Descriptor instead.
func (*GetForestsByUserResponse) Descriptor() ([]byte, []int) {
	return file_protos_forest_forest_proto_rawDescGZIP(), []int{5}
}

func (x *GetForestsByUserResponse) GetForests() []*Forest {
	if x != nil {
		return x.Forests
	}
	return nil
}

type GetForestRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ForestId        string                 `protobuf:"bytes,1,opt,name=forest_id,json=forestId,proto3" json:"forest_id,omitempty"`
	IncludeChildren bool                   `protobuf:"varint,2,opt,name=include_children,json=includeChildren,proto3" json:"include_children,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetForestRequest) Reset() {
	*x = GetForestRequest{}
	mi := &file_protos_forest_forest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForestRequest) ProtoMessage() {}

func (x *GetForestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_forest_forest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForestRequest.ProtoReflect.Descriptor instead.
func (*GetForestRequest) Descriptor() ([]byte, []int) {
	return file_protos_forest_forest_proto_rawDescGZIP(), []int{6}
}

func (x *GetForestRequest) GetForestId() string {
	if x != nil {
		return x.ForestId
	}
	return ""
}

func (x *GetForestRequest) GetIncludeChildren() bool {
	if x != nil {
		return x.IncludeChildren
	}
	return false
}

type GetForestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Forest        *Forest                `protobuf:"bytes,1,opt,name=forest,proto3" json:"forest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForestResponse) Reset() {
	*x = GetForestResponse{}
	mi := &file_protos_forest_forest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForestResponse) ProtoMessage() {}

func (x *GetForestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_forest_forest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForestResponse.ProtoReflect.Descriptor instead.
func (*GetForestResponse) Descriptor() ([]byte, []int) {
	return file_protos_forest_forest_proto_rawDescGZIP(), []int{7}
}

func (x *GetForestResponse) GetForest() *Forest {
	if x != nil {
		return x.Forest
	}
	return nil
}

type UpdateForestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ForestId      string                 `protobuf:"bytes,1,opt,name=forest_id,json=forestId,proto3" json:"forest_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateForestRequest) Reset() {
	*x = UpdateForestRequest{}
	mi := &file_protos_forest_forest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateForestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateForestRequest) ProtoMessage() {}

func (x *UpdateForestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_forest_forest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateForestRequest.ProtoReflect.Descriptor instead.
func (*UpdateForestRequest) Descriptor() ([]byte, []int) {
	return file_protos_forest_forest_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateForestRequest) GetForestId() string {
	if x != nil {
		return x.ForestId
	}
	return ""
}

func (x *UpdateForestRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateForestRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Forest 삭제 RPC
type DeleteForestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ForestId      string                 `protobuf:"bytes,1,opt,name=forest_id,json=forestId,proto3" json:"forest_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteForestRequest) Reset() {
	*x = DeleteForestRequest{}
	mi := &file_protos_forest_forest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteForestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteForestRequest) ProtoMessage() {}

func (x *DeleteForestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_forest_forest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteForestRequest.ProtoReflect.Descriptor instead.
func (*DeleteForestRequest) Descriptor() ([]byte, []int) {
	return file_protos_forest_forest_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteForestRequest) GetForestId() string {
	if x != nil {
		return x.ForestId
	}
	return ""
}

type DeleteForestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteForestResponse) Reset() {
	*x = DeleteForestResponse{}
	mi := &file_protos_forest_forest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteForestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteForestResponse) ProtoMessage() {}

func (x *DeleteForestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_forest_forest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteForestResponse.ProtoReflect.Descriptor instead.
func (*DeleteForestResponse) Descriptor() ([]byte, []int) {
	return file_protos_forest_forest_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteForestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TreeId        string                 `protobuf:"bytes,1,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTreeRequest) Reset() {
	*x = UpdateTreeRequest{}
	mi := &file_protos_forest_forest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTreeRequest) ProtoMessage() {}

func (x *UpdateTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_forest_forest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTreeRequest.ProtoReflect.Descriptor instead.
func (*UpdateTreeRequest) Descriptor() ([]byte, []int) {
	return file_protos_forest_forest_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateTreeRequest) GetTreeId() string {
	if x != nil {
		return x.TreeId
	}
	return ""
}

func (x *UpdateTreeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTreeRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type DeleteTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TreeId        string                 `protobuf:"bytes,1,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	Cascade       bool                   `protobuf:"varint,2,opt,name=cascade,proto3" json:"cascade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTreeRequest) Reset() {
	*x = DeleteTreeRequest{}
	mi := &file_protos_forest_forest_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTreeRequest) ProtoMessage() {}

func (x *DeleteTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_forest_forest_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTreeRequest.ProtoReflect.Descriptor instead.
func (*DeleteTreeRequest) Descriptor() ([]byte, []int) {
	return file_protos_forest_forest_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteTreeRequest) GetTreeId() string {
	if x != nil {
		return x.TreeId
	}
	return ""
}

func (x *DeleteTreeRequest) GetCascade() bool {
	if x != nil {
		return x.Cascade
	}
	return false
}

type DeleteTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTreeResponse) Reset() {
	*x = DeleteTreeResponse{}
	mi := &file_protos_forest_forest_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTreeResponse) ProtoMessage() {}

func (x *DeleteTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_forest_forest_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTreeResponse.ProtoReflect.Descriptor instead.
func (*DeleteTreeResponse) Descriptor() ([]byte, []int) {
	return file_protos_forest_forest_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteTreeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetTreeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TreeId          string                 `protobuf:"bytes,1,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	IncludeChildren bool                   `protobuf:"varint,2,opt,name=include_children,json=includeChildren,proto3" json:"include_children,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetTreeRequest) Reset() {
	*x = GetTreeRequest{}
	mi := &file_protos_forest_forest_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTreeRequest) ProtoMessage() {}

func (x *GetTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_forest_forest_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTreeRequest.ProtoReflect.Descriptor instead.
func (*GetTreeRequest) Descriptor() ([]byte, []int) {
	return file_protos_forest_forest_proto_rawDescGZIP(), []int{14}
}

func (x *GetTreeRequest) GetTreeId() string {
	if x != nil {
		return x.TreeId
	}
	return ""
}

func (x *GetTreeRequest) GetIncludeChildren() bool {
	if x != nil {
		return x.IncludeChildren
	}
	return false
}

var File_protos_forest_forest_proto protoreflect.FileDescriptor

const file_protos_forest_forest_proto_rawDesc = "" +
	"\n" +
	"\x1aprotos/forest/forest.proto\"D\n" +
	"\x17GetForestsByUserRequest\x12)\n" +
	"\x10include_children\x18\x01 \x01(\bR\x0fincludeChildren\"_\n" +
	"\x04Tree\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12!\n" +
	"\bchildren\x18\x04 \x03(\v2\x05.TreeR\bchildren\"f\n" +
	"\x11CreateTreeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\tR\bparentId\"\xb9\x01\n" +
	"\x06Forest\x12\x19\n" +
	"\x04root\x18\x01 \x01(\v2\x05.TreeR\x04root\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05depth\x18\x05 \x01(\x05R\x05depth\x12\x1f\n" +
	"\vtotal_trees\x18\x06 \x01(\x05R\n" +
	"totalTrees\x12\x17\n" +
	"\auser_id\x18\a \x01(\tR\x06userId\"f\n" +
	"\x13CreateForestRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x19\n" +
	"\x04root\x18\x04 \x01(\v2\x05.TreeR\x04root\"=\n" +
	"\x18GetForestsByUserResponse\x12!\n" +
	"\aforests\x18\x01 \x03(\v2\a.ForestR\aforests\"Z\n" +
	"\x10GetForestRequest\x12\x1b\n" +
	"\tforest_id\x18\x01 \x01(\tR\bforestId\x12)\n" +
	"\x10include_children\x18\x02 \x01(\bR\x0fincludeChildren\"4\n" +
	"\x11GetForestResponse\x12\x1f\n" +
	"\x06forest\x18\x01 \x01(\v2\a.ForestR\x06forest\"h\n" +
	"\x13UpdateForestRequest\x12\x1b\n" +
	"\tforest_id\x18\x01 \x01(\tR\bforestId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"2\n" +
	"\x13DeleteForestRequest\x12\x1b\n" +
	"\tforest_id\x18\x01 \x01(\tR\bforestId\"0\n" +
	"\x14DeleteForestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"R\n" +
	"\x11UpdateTreeRequest\x12\x17\n" +
	"\atree_id\x18\x01 \x01(\tR\x06treeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"F\n" +
	"\x11DeleteTreeRequest\x12\x17\n" +
	"\atree_id\x18\x01 \x01(\tR\x06treeId\x12\x18\n" +
	"\acascade\x18\x02 \x01(\bR\acascade\".\n" +
	"\x12DeleteTreeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"T\n" +
	"\x0eGetTreeRequest\x12\x17\n" +
	"\atree_id\x18\x01 \x01(\tR\x06treeId\x12)\n" +
	"\x10include_children\x18\x02 \x01(\bR\x0fincludeChildren2\xd3\x03\n" +
	"\rForestService\x12G\n" +
	"\x10GetForestsByUser\x12\x18.GetForestsByUserRequest\x1a\x19.GetForestsByUserResponse\x12-\n" +
	"\fCreateForest\x12\x14.CreateForestRequest\x1a\a.Forest\x12'\n" +
	"\n" +
	"CreateTree\x12\x12.CreateTreeRequest\x1a\x05.Tree\x122\n" +
	"\tGetForest\x12\x11.GetForestRequest\x1a\x12.GetForestResponse\x12-\n" +
	"\fUpdateForest\x12\x14.UpdateForestRequest\x1a\a.Forest\x12;\n" +
	"\fDeleteForest\x12\x14.DeleteForestRequest\x1a\x15.DeleteForestResponse\x12'\n" +
	"\n" +
	"UpdateTree\x12\x12.UpdateTreeRequest\x1a\x05.Tree\x125\n" +
	"\n" +
	"DeleteTree\x12\x12.DeleteTreeRequest\x1a\x13.DeleteTreeResponse\x12!\n" +
	"\aGetTree\x12\x0f.GetTreeRequest\x1a\x05.TreeB2Z0github.com/jdk829355/InForest_back/protos/forestb\x06proto3"

var (
	file_protos_forest_forest_proto_rawDescOnce sync.Once
	file_protos_forest_forest_proto_rawDescData []byte
)

func file_protos_forest_forest_proto_rawDescGZIP() []byte {
	file_protos_forest_forest_proto_rawDescOnce.Do(func() {
		file_protos_forest_forest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_forest_forest_proto_rawDesc), len(file_protos_forest_forest_proto_rawDesc)))
	})
	return file_protos_forest_forest_proto_rawDescData
}

var file_protos_forest_forest_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_protos_forest_forest_proto_goTypes = []any{
	(*GetForestsByUserRequest)(nil),  // 0: GetForestsByUserRequest
	(*Tree)(nil),                     // 1: Tree
	(*CreateTreeRequest)(nil),        // 2: CreateTreeRequest
	(*Forest)(nil),                   // 3: Forest
	(*CreateForestRequest)(nil),      // 4: CreateForestRequest
	(*GetForestsByUserResponse)(nil), // 5: GetForestsByUserResponse
	(*GetForestRequest)(nil),         // 6: GetForestRequest
	(*GetForestResponse)(nil),        // 7: GetForestResponse
	(*UpdateForestRequest)(nil),      // 8: UpdateForestRequest
	(*DeleteForestRequest)(nil),      // 9: DeleteForestRequest
	(*DeleteForestResponse)(nil),     // 10: DeleteForestResponse
	(*UpdateTreeRequest)(nil),        // 11: UpdateTreeRequest
	(*DeleteTreeRequest)(nil),        // 12: DeleteTreeRequest
	(*DeleteTreeResponse)(nil),       // 13: DeleteTreeResponse
	(*GetTreeRequest)(nil),           // 14: GetTreeRequest
}
var file_protos_forest_forest_proto_depIdxs = []int32{
	1,  // 0: Tree.children:type_name -> Tree
	1,  // 1: Forest.root:type_name -> Tree
	1,  // 2: CreateForestRequest.root:type_name -> Tree
	3,  // 3: GetForestsByUserResponse.forests:type_name -> Forest
	3,  // 4: GetForestResponse.forest:type_name -> Forest
	0,  // 5: ForestService.GetForestsByUser:input_type -> GetForestsByUserRequest
	4,  // 6: ForestService.CreateForest:input_type -> CreateForestRequest
	2,  // 7: ForestService.CreateTree:input_type -> CreateTreeRequest
	6,  // 8: ForestService.GetForest:input_type -> GetForestRequest
	8,  // 9: ForestService.UpdateForest:input_type -> UpdateForestRequest
	9,  // 10: ForestService.DeleteForest:input_type -> DeleteForestRequest
	11, // 11: ForestService.UpdateTree:input_type -> UpdateTreeRequest
	12, // 12: ForestService.DeleteTree:input_type -> DeleteTreeRequest
	14, // 13: ForestService.GetTree:input_type -> GetTreeRequest
	5,  // 14: ForestService.GetForestsByUser:output_type -> GetForestsByUserResponse
	3,  // 15: ForestService.CreateForest:output_type -> Forest
	1,  // 16: ForestService.CreateTree:output_type -> Tree
	7,  // 17: ForestService.GetForest:output_type -> GetForestResponse
	3,  // 18: ForestService.UpdateForest:output_type -> Forest
	10, // 19: ForestService.DeleteForest:output_type -> DeleteForestResponse
	1,  // 20: ForestService.UpdateTree:output_type -> Tree
	13, // 21: ForestService.DeleteTree:output_type -> DeleteTreeResponse
	1,  // 22: ForestService.GetTree:output_type -> Tree
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_protos_forest_forest_proto_init() }
func file_protos_forest_forest_proto_init() {
	if File_protos_forest_forest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_forest_forest_proto_rawDesc), len(file_protos_forest_forest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_forest_forest_proto_goTypes,
		DependencyIndexes: file_protos_forest_forest_proto_depIdxs,
		MessageInfos:      file_protos_forest_forest_proto_msgTypes,
	}.Build()
	File_protos_forest_forest_proto = out.File
	file_protos_forest_forest_proto_goTypes = nil
	file_protos_forest_forest_proto_depIdxs = nil
}
