// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: forest.proto

package forest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ForestService_GetForestsByUser_FullMethodName = "/ForestService/GetForestsByUser"
	ForestService_CreateForest_FullMethodName     = "/ForestService/CreateForest"
	ForestService_CreateTree_FullMethodName       = "/ForestService/CreateTree"
	ForestService_GetForest_FullMethodName        = "/ForestService/GetForest"
)

// ForestServiceClient is the client API for ForestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ForestServiceClient interface {
	GetForestsByUser(ctx context.Context, in *GetForestsByUserRequest, opts ...grpc.CallOption) (*GetForestsByUserResponse, error)
	CreateForest(ctx context.Context, in *CreateForestRequest, opts ...grpc.CallOption) (*Forest, error)
	CreateTree(ctx context.Context, in *CreateTreeRequest, opts ...grpc.CallOption) (*Tree, error)
	GetForest(ctx context.Context, in *GetForestRequest, opts ...grpc.CallOption) (*GetForestResponse, error)
}

type forestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewForestServiceClient(cc grpc.ClientConnInterface) ForestServiceClient {
	return &forestServiceClient{cc}
}

func (c *forestServiceClient) GetForestsByUser(ctx context.Context, in *GetForestsByUserRequest, opts ...grpc.CallOption) (*GetForestsByUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetForestsByUserResponse)
	err := c.cc.Invoke(ctx, ForestService_GetForestsByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forestServiceClient) CreateForest(ctx context.Context, in *CreateForestRequest, opts ...grpc.CallOption) (*Forest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Forest)
	err := c.cc.Invoke(ctx, ForestService_CreateForest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forestServiceClient) CreateTree(ctx context.Context, in *CreateTreeRequest, opts ...grpc.CallOption) (*Tree, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tree)
	err := c.cc.Invoke(ctx, ForestService_CreateTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forestServiceClient) GetForest(ctx context.Context, in *GetForestRequest, opts ...grpc.CallOption) (*GetForestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetForestResponse)
	err := c.cc.Invoke(ctx, ForestService_GetForest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ForestServiceServer is the server API for ForestService service.
// All implementations must embed UnimplementedForestServiceServer
// for forward compatibility.
type ForestServiceServer interface {
	GetForestsByUser(context.Context, *GetForestsByUserRequest) (*GetForestsByUserResponse, error)
	CreateForest(context.Context, *CreateForestRequest) (*Forest, error)
	CreateTree(context.Context, *CreateTreeRequest) (*Tree, error)
	GetForest(context.Context, *GetForestRequest) (*GetForestResponse, error)
	mustEmbedUnimplementedForestServiceServer()
}

// UnimplementedForestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedForestServiceServer struct{}

func (UnimplementedForestServiceServer) GetForestsByUser(context.Context, *GetForestsByUserRequest) (*GetForestsByUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetForestsByUser not implemented")
}
func (UnimplementedForestServiceServer) CreateForest(context.Context, *CreateForestRequest) (*Forest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateForest not implemented")
}
func (UnimplementedForestServiceServer) CreateTree(context.Context, *CreateTreeRequest) (*Tree, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTree not implemented")
}
func (UnimplementedForestServiceServer) GetForest(context.Context, *GetForestRequest) (*GetForestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetForest not implemented")
}
func (UnimplementedForestServiceServer) mustEmbedUnimplementedForestServiceServer() {}
func (UnimplementedForestServiceServer) testEmbeddedByValue()                       {}

// UnsafeForestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForestServiceServer will
// result in compilation errors.
type UnsafeForestServiceServer interface {
	mustEmbedUnimplementedForestServiceServer()
}

func RegisterForestServiceServer(s grpc.ServiceRegistrar, srv ForestServiceServer) {
	// If the following call pancis, it indicates UnimplementedForestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ForestService_ServiceDesc, srv)
}

func _ForestService_GetForestsByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetForestsByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForestServiceServer).GetForestsByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForestService_GetForestsByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForestServiceServer).GetForestsByUser(ctx, req.(*GetForestsByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForestService_CreateForest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateForestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForestServiceServer).CreateForest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForestService_CreateForest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForestServiceServer).CreateForest(ctx, req.(*CreateForestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForestService_CreateTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForestServiceServer).CreateTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForestService_CreateTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForestServiceServer).CreateTree(ctx, req.(*CreateTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForestService_GetForest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetForestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForestServiceServer).GetForest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForestService_GetForest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForestServiceServer).GetForest(ctx, req.(*GetForestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ForestService_ServiceDesc is the grpc.ServiceDesc for ForestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ForestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ForestService",
	HandlerType: (*ForestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetForestsByUser",
			Handler:    _ForestService_GetForestsByUser_Handler,
		},
		{
			MethodName: "CreateForest",
			Handler:    _ForestService_CreateForest_Handler,
		},
		{
			MethodName: "CreateTree",
			Handler:    _ForestService_CreateTree_Handler,
		},
		{
			MethodName: "GetForest",
			Handler:    _ForestService_GetForest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "forest.proto",
}
